@baseUrl = http://localhost:7071/api 
@controller = InboxDetails
@uri = {{baseUrl}}/{{controller}}
@targetFolder = Toppers


###
# @name GetAllEmails
GET {{baseUrl}}/GetAllEmails

###
# @name GetFolderMailSubjectLines
GET {{uri}}/GetFolderMailSubjectLines
    ?folder={{targetFolder}}